"""add is_favorite column to notes table

Revision ID: 0486227a5f85
Revises: 8cbe2ffc5dc3
Create Date: 2026-01-05 16:38:39.269058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0486227a5f85'
down_revision: Union[str, None] = '8cbe2ffc5dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_favorite')
    # ### end Alembic commands ###
