"""add color to notes

Revision ID: c75717b27abb
Revises: 0486227a5f85
Create Date: 2026-01-15 14:20:44.952173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c75717b27abb'
down_revision: Union[str, None] = '0486227a5f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'color')
    # ### end Alembic commands ###
